/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PointsTableRouteImport } from './routes/points-table'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as LiveMatchIdRouteImport } from './routes/live.$matchId'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiLiveMatchesRouteImport } from './routes/api/live-matches'
import { Route as ApiMatchIdRouteImport } from './routes/api/match.$id'
import { Route as ApiLiveIdRouteImport } from './routes/api/live.$id'
import { Route as ApiCommentaryIdRouteImport } from './routes/api/commentary.$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsTableRoute = PointsTableRouteImport.update({
  id: '/points-table',
  path: '/points-table',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMatchIdRoute = LiveMatchIdRouteImport.update({
  id: '/live/$matchId',
  path: '/live/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveMatchesRoute = ApiLiveMatchesRouteImport.update({
  id: '/api/live-matches',
  path: '/api/live-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchIdRoute = ApiMatchIdRouteImport.update({
  id: '/api/match/$id',
  path: '/api/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveIdRoute = ApiLiveIdRouteImport.update({
  id: '/api/live/$id',
  path: '/api/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentaryIdRoute = ApiCommentaryIdRouteImport.update({
  id: '/api/commentary/$id',
  path: '/api/commentary/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/news': typeof NewsRoute
  '/players': typeof PlayersRoute
  '/points-table': typeof PointsTableRoute
  '/stats': typeof StatsRoute
  '/teams': typeof TeamsRoute
  '/videos': typeof VideosRoute
  '/api/live-matches': typeof ApiLiveMatchesRoute
  '/api/news': typeof ApiNewsRoute
  '/live/$matchId': typeof LiveMatchIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/api/commentary/$id': typeof ApiCommentaryIdRoute
  '/api/live/$id': typeof ApiLiveIdRoute
  '/api/match/$id': typeof ApiMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/news': typeof NewsRoute
  '/players': typeof PlayersRoute
  '/points-table': typeof PointsTableRoute
  '/stats': typeof StatsRoute
  '/teams': typeof TeamsRoute
  '/videos': typeof VideosRoute
  '/api/live-matches': typeof ApiLiveMatchesRoute
  '/api/news': typeof ApiNewsRoute
  '/live/$matchId': typeof LiveMatchIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/api/commentary/$id': typeof ApiCommentaryIdRoute
  '/api/live/$id': typeof ApiLiveIdRoute
  '/api/match/$id': typeof ApiMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/news': typeof NewsRoute
  '/players': typeof PlayersRoute
  '/points-table': typeof PointsTableRoute
  '/stats': typeof StatsRoute
  '/teams': typeof TeamsRoute
  '/videos': typeof VideosRoute
  '/api/live-matches': typeof ApiLiveMatchesRoute
  '/api/news': typeof ApiNewsRoute
  '/live/$matchId': typeof LiveMatchIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/api/commentary/$id': typeof ApiCommentaryIdRoute
  '/api/live/$id': typeof ApiLiveIdRoute
  '/api/match/$id': typeof ApiMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matches'
    | '/news'
    | '/players'
    | '/points-table'
    | '/stats'
    | '/teams'
    | '/videos'
    | '/api/live-matches'
    | '/api/news'
    | '/live/$matchId'
    | '/team/$teamId'
    | '/api/commentary/$id'
    | '/api/live/$id'
    | '/api/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matches'
    | '/news'
    | '/players'
    | '/points-table'
    | '/stats'
    | '/teams'
    | '/videos'
    | '/api/live-matches'
    | '/api/news'
    | '/live/$matchId'
    | '/team/$teamId'
    | '/api/commentary/$id'
    | '/api/live/$id'
    | '/api/match/$id'
  id:
    | '__root__'
    | '/'
    | '/matches'
    | '/news'
    | '/players'
    | '/points-table'
    | '/stats'
    | '/teams'
    | '/videos'
    | '/api/live-matches'
    | '/api/news'
    | '/live/$matchId'
    | '/team/$teamId'
    | '/api/commentary/$id'
    | '/api/live/$id'
    | '/api/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesRoute: typeof MatchesRoute
  NewsRoute: typeof NewsRoute
  PlayersRoute: typeof PlayersRoute
  PointsTableRoute: typeof PointsTableRoute
  StatsRoute: typeof StatsRoute
  TeamsRoute: typeof TeamsRoute
  VideosRoute: typeof VideosRoute
  ApiLiveMatchesRoute: typeof ApiLiveMatchesRoute
  ApiNewsRoute: typeof ApiNewsRoute
  LiveMatchIdRoute: typeof LiveMatchIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
  ApiCommentaryIdRoute: typeof ApiCommentaryIdRoute
  ApiLiveIdRoute: typeof ApiLiveIdRoute
  ApiMatchIdRoute: typeof ApiMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points-table': {
      id: '/points-table'
      path: '/points-table'
      fullPath: '/points-table'
      preLoaderRoute: typeof PointsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$matchId': {
      id: '/live/$matchId'
      path: '/live/$matchId'
      fullPath: '/live/$matchId'
      preLoaderRoute: typeof LiveMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-matches': {
      id: '/api/live-matches'
      path: '/api/live-matches'
      fullPath: '/api/live-matches'
      preLoaderRoute: typeof ApiLiveMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match/$id': {
      id: '/api/match/$id'
      path: '/api/match/$id'
      fullPath: '/api/match/$id'
      preLoaderRoute: typeof ApiMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/$id': {
      id: '/api/live/$id'
      path: '/api/live/$id'
      fullPath: '/api/live/$id'
      preLoaderRoute: typeof ApiLiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commentary/$id': {
      id: '/api/commentary/$id'
      path: '/api/commentary/$id'
      fullPath: '/api/commentary/$id'
      preLoaderRoute: typeof ApiCommentaryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesRoute: MatchesRoute,
  NewsRoute: NewsRoute,
  PlayersRoute: PlayersRoute,
  PointsTableRoute: PointsTableRoute,
  StatsRoute: StatsRoute,
  TeamsRoute: TeamsRoute,
  VideosRoute: VideosRoute,
  ApiLiveMatchesRoute: ApiLiveMatchesRoute,
  ApiNewsRoute: ApiNewsRoute,
  LiveMatchIdRoute: LiveMatchIdRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
  ApiCommentaryIdRoute: ApiCommentaryIdRoute,
  ApiLiveIdRoute: ApiLiveIdRoute,
  ApiMatchIdRoute: ApiMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
